module.exports = {
  STATUSES: ["FINISHED", "RELEASING", "NOT_YET_RELEASED", "CANCELLED", "HIATUS"],
  CATEGORIES: ["Everything", "Watching", "Completed", "Plan to Watch", "On Hold", "Dropped"],
  GENRES: [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Fantasy",
    "Sci-Fi",
    "Romance",
    "Supernatural",
    "Thriller",
    "Horror",
    "Psychological",
    "Slice of Life",
    "Sports",
    "Mecha",
    "Music",
  ],
};
